### ISSUE TITLE
Revise granule cell hierarchy to add more detail.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2012]
The general class 'granule cell' now has a definition, but this is necessarily vague given that this is a grouping of likely unrelated neuron types, all of which are small.

This means that 'granule cell' is  uninformative as a genus.  The logical and textual definitions of types of granule cell should therefore be revised from the very simple genus-type definitions currently present.

e.g. 

cerebellar granule cell
http://purl.obolibrary.org/obo/CL_0001031
Granule cell that is part of the cerebellum.

Wikipedia has nice potted descriptions of these.  e.g. https://en.wikipedia.org/wiki/Granule_cell#Cerebellar_granule_cell

-> A neuron with a very small soma located in the granule cell layer cerebral cortex.  It develops from precursors in the rhombic lip. These cells have several short dendrites which terminate with claw-shaped endings and a single axon that ascends into the molecular layer where it splits to form parallel fibers.

Updates to logical axoms

-  consider restricting soma location to granular layer of cerebellar cortex http://purl.obolibrary.org/obo/UBERON_0002956
-  add develops_from axiom to 'rhombic lip' (Note - there is an extensive literature on this that could potentially be mined for details
- add has_part relationship to parallel fiber http://purl.obolibrary.org/obo/GO_1990032

**Comment by bvarner-ebi** [comment]
![Image](https://github.com/obophenotype/cell-ontology/assets/95643797/121cdafa-daff-4855-b114-30cfcb1fa38e)



Class | Revisions
-- | --
[cerebellar granule cell ](http://purl.obolibrary.org/obo/CL_0001031)| See above
[cortical granule cell](http://purl.obolibrary.org/obo/CL_0001032) | Broad / general class. No change.
[hippocampal granule cell](http://purl.obolibrary.org/obo/CL_0001033) | Broad / general class. No change.
[dentate gyrus of hippocampal formation granule cell](http://purl.obolibrary.org/obo/CL_2000089)| Promote comment to definition.
[Island of Calleja granule cell](http://purl.obolibrary.org/obo/CL_4030053)| Done
[olfactory granule cell](http://purl.obolibrary.org/obo/CL_0000626) | TBD

**Comment by dosumis** [comment]
See #1980 for examples of classification based on derivation from upper/lower rhombic lip.

**Comment by bvarner-ebi** [comment]
### Edits for '[cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031)'
----
- [ ] **Edit text definition**:

**CURRENT**: "Granule cell that is part of the cerebellum."

**PROPOSED**: "An excitatory granule cell with a soma located in the granular layer of cerebellar cortex. In an adult, a cerebellar granule cell has short dendrites with a characteristic claw-like appearance and a long axon that ascends to the molecular layer where it bifurcates and extends mediolaterally to form parallel fibers."
doi:10.3389/fncir.2020.611841
doi:10.12688/f1000research.15021.1

- [ ] **Add axioms**:

- `SubClass of some 'glutamatergic neuron'`
- `'directly develops from' some 'granule cell precursor'` (relabel object to cerebellar granule cell precursor'

- [ ] **Add comment**:
It has been noted in at least some mammalian species that granule cells are the most numerous cell type in the cerebellum and in the brain, with at least 99% of all cerebellar neurons being granule cells. 
doi:10.3389/fncir.2020.611841

Related edits for '[**granule cell precursor**](http://purl.obolibrary.org/obo/CL_0002362)':

- [ ] **Edit label of 'granule cell precursor'**:

**CURRENT**: 'granule cell precursor'

**PROPOSED**: 'cerebellar granule cell precursor'

**REASON**: The text def and dbxref are specific to cerebellar granule cell precursors.

- [ ] **Add synonyms to relabeled class**:
- "granule cell precursor", broad, doi:10.3389/fncir.2020.611841
- "granule cell progenitor", exact, doi:10.3389/fncir.2020.611841
- "GCP", related, abbr, doi:10.3389/fncir.2020.611841

- [ ] **Edit text def of 'granule cell precursor'**:

- change "NK-1 positive" to "HNK1-positive" (keep PMID dbxref)

- [ ] **Add axiom to 'granule cell precursor'**:

- `'part of' some 'upper rhombic lip'` (import term)

**Comment by bvarner-ebi** [comment]
### Edits for [‘dentate gyrus of hippocampal formation granule cell’](http://purl.obolibrary.org/obo/CL_2000089)
----
- [ ] **Edit text definition**:

**CURRENT**: "The principal cell type of the dentate gyrus."

**PROPOSED**: “A granule cell that has soma location in the dentate gyrus cell layer of the hippocampal formation and has an elliptical cell body and characteristic cone-shaped tree of spiny apical dendrites. The branches extend throughout the molecular layer and the distal tips of the dendritic tree end just at the hippocampal fissure or at the ventricular surface. The dentate gyrus of hippocampal formation granule cell is the principal cell type of the dentate gyrus.” PMID:[17765709](https://pubmed.ncbi.nlm.nih.gov/17765709)


- [ ] **Edit logical definition** (make more precise):

**CURRENT**: 'granule cell'
 and ('has soma location' some 'dentate gyrus of hippocampal formation')

**PROPOSED**: ‘hippocampal granule cell'
 and ('has soma location' some 'dentate gyrus granule cell layer’)

- [ ] **Edit comment**:

**CURRENT**: “The granule cell has a characteristic cone-shaped tree of spiny apical dendrites.”

**PROPOSED**: “As far as can be determined, all dentate granule cells appear to project to CA3 and the axon trajectory is partially correlated with the position of the parent cell body.”
PMID:[17765709](https://pubmed.ncbi.nlm.nih.gov/17765709)


**Related edits for [dentate gyrus mossy fiber](http://purl.obolibrary.org/obo/GO_0044302)**:

- [ ] delete has_exact_synonym “granule cell axon” (consider ‘parallel fiber’)
or 
make it a broad synonym

- [ ] **Edit axiom**:

**CURRENT**: 'part of' some 'granule cell'
**PROPOSED**: 'part of' some 'dentate gyrus of hippocampal formation granule cell’

**Comment by dosumis** [comment]
> Edits for '[cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031)'

Once all axioms are in place please check whether the DL query 'develops from' some 'upper rhombic lip' returns this cell type.

**Comment by bvarner-ebi** [comment]
> > Edits for [‘dentate gyrus of hippocampal formation granule cell’](http://purl.obolibrary.org/obo/CL_2000089)
> 
> Looks good but please simplify name: suggest: dentate gyrus granule cell

[Added to action items above. ](https://github.com/obophenotype/cell-ontology/issues/2012#issuecomment-1633906422)Will add current label as an exact syn.

**Comment by bvarner-ebi** [comment]
> > Edits for '[cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031)'
> 
> Once all axioms are in place please check whether the DL query 'develops from' some 'upper rhombic lip' returns this cell type.

Looks like it does:

<img width="647" alt="Screenshot 2023-07-17 at 17 46 32" src="https://github.com/obophenotype/cell-ontology/assets/95643797/e8ef3148-7fb0-45d8-aba3-ba891e25d74c">

**Comment by raymond91125** [comment]
I wonder if hippocampal granule cell and dentate gyrus granule cell should be exact synonyms. 
That is, are there hippocampal granule cells not of dentate gyrus?
Not in these two articles.
https://en.wikipedia.org/wiki/Hippocampus_anatomy
https://en.wikipedia.org/wiki/Granule_cell

**Comment by bvarner-ebi** [comment]
> I wonder if hippocampal granule cell and dentate gyrus granule cell should be exact synonyms.
> That is, are there hippocampal granule cells not of dentate gyrus?
> Not in these two articles.
> https://en.wikipedia.org/wiki/Hippocampus_anatomy
> https://en.wikipedia.org/wiki/Granule_cell

Thanks for the suggestion, @raymond91125. 
A cursory online literature search revealed at least one instance of granule cells described in the hippocampus outside of the DG: https://www.jneurosci.org/content/30/24/8296

**Comment by bvarner-ebi** [comment]
### Edits for '[olfactory granule cell](http://purl.obolibrary.org/obo/CL_0000626)'
----

- [ ] **Edit text definition**:

**CURRENT**: "Granule cell that is part of the olfactory bulb."

**PROPOSED**: "A granule cell that has a soma located in an olfactory bulb granule cell layer. An olfactory granule cell is an interneuron that lacks an axon, makes reciprocal dendro-dendritic synapses with mitral cells and tufted cells and is involved in the fine spatio-temporal tuning of the responses of these principal olfactory bulb neurons to odors."
DOI:10.1038/s41598-018-27692-8

- [ ] **Add synonyms**:

"olfactory bulb granule cell" (exact, DOI:10.1038/s41598-018-27692-8)
"GCs" (related, plural, DOI:10.1038/s41598-018-27692-8)

- [ ] **Change logical definition**:

**CURRENT**: 'granule cell' and ('has soma location' some 'olfactory bulb')

**PROPOSED**: 'granule cell' and ('has soma location' some 'olfactory bulb granule cell layer')

- [ ] **Remove SubClass Of '[granule cell](http://purl.obolibrary.org/obo/CL_0000120)'** (redundant)

- [ ] **Add axioms**:
- SubClass Of some [interneuron](http://purl.obolibrary.org/obo/CL_0000099)
- ‘[synapsed by](http://purl.obolibrary.org/obo/RO_0002103)’ some ‘[mitral cell](http://purl.obolibrary.org/obo/CL_1001502)’
- ‘[synapsed to](http://purl.obolibrary.org/obo/RO_0002120)’ some ‘[mitral cell](http://purl.obolibrary.org/obo/CL_1001502)’
- ‘[synapsed by](http://purl.obolibrary.org/obo/RO_0002103)’ some ‘[olfactory bulb tufted cell](http://purl.obolibrary.org/obo/CL_1001503)’
- ‘[synapsed to](http://purl.obolibrary.org/obo/RO_0002120)’ some ‘[olfactory bulb tufted cell](http://purl.obolibrary.org/obo/CL_1001503)’
- ‘[involved in regulation of](http://purl.obolibrary.org/obo/RO_0002428)’ some ‘[sensory perception of cell](http://purl.obolibrary.org/obo/GO_0007608)’

- [ ] **Add comment**:

"Granule cells are the most abundant neuronal population in the olfactory bulb and are continuously renewed throughout life."
DOI:10.1038/s41598-018-27692-8
