### ISSUE TITLE
Links to GO terms for types of cilia and villi

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2305]
Background:  I would like a general push on improving links to cell component terms in GO. I'd like to start with a focus on cleaning up terms for ciliated cell types.

<img width="482" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/5e8d0661-f181-4b03-a8e4-bd802d5608a9">

Issues:

1. The current structure includes cells that are not ciliated, but instead have microvilli.  These are the brush border epithelial cells.  GO has a term for microvillus that we can link these to (unfortunately it does not have a term for brush border, but we could request.
2. Ideally we would distinguish motile from immotile cilia & link to the appropriate term in GO.  I think all of the multiciliated epithelial cells have motile cilia.  Also I believe ependymal cells are well known examples of multicilliated cells  
3. 'single cilliated cell' is a slightly odd term in that I believe most cells have one immotile cilium, which sometimes has a specialised function.  Sperm has one motile cilium so strictly should be under ciliated (classification will be automated by adding has_part 'sperm flagellum'
4. We lack textual definitions for a number of cells including brush border cell and have rather minimal defs for others.

```[tasklist]
### Tasks
- [ ] https://github.com/obophenotype/cell-ontology/pull/2440
- [ ] https://github.com/obophenotype/cell-ontology/pull/2384
- [ ] https://github.com/obophenotype/cell-ontology/pull/2401
- [ ] https://github.com/obophenotype/cell-ontology/issues/2456
- [ ] https://github.com/obophenotype/cell-ontology/issues/2458
- [ ] https://github.com/obophenotype/cell-ontology/issues/2460
```

**Comment by dosumis** [comment]
Hi @Caroline-99 & @aleixpuigb  - I'm co-assigning this one as perhaps not an ideal early ticket.  However, it is a good example of how I would like to clean up links to GO - which will be one of the themes of Caroline's work.

**Comment by dosumis** [comment]
IIRC there is no relationship to villi and the term is defined for
epithelia not epithelial cells.  We could request that GO fix, but will
need a work around if this takes time.

**Comment by dosumis** [comment]
Sorry - ignore last comment.  GO term looks good https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0005903
