### ISSUE TITLE
Add region specific cortical cell types 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2330]
Jorstad, Nikolas L., Jennie Close, Nelson Johansen, Anna Marie Yanny, Eliza R. Barkan, Kyle J. Travaglini, Darren Bertagnolli, et al. 2023. “Transcriptomic Cytoarchitecture Reveals Principles of Human Neocortex Organization.” Science 382 (6667): eadf6812. https://doi.org/10.1126/science.adf6812.

This paper identifies a number of cell types that are only found in specific cortical regions - visual cortex in particular:

<img width="1384" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/b7c0037a-5e9d-4f27-b779-00ceff02fbb7">

In order to add these to CL we would need distinguishing properties.   Laminar location and grouping by well known marker (SST) may work in some cases, but in both of these cases, it is important to pay attention to the details. e.g. L4 is a transcriptomic grouping that does not correspond strictly to location in L4 - but ~to L4.  SST as a transcriptomic grouping may not correspond to SST expression in all subtypes.

NS-Forest markers would be ideal solution to finding distinguishing properties @scheuerm - did you & Renne already do work on these?  

I think that these are also candidates for adding data-linked definitions to terms in CL (currently only in PCL).

Potential issue - naming via simple numbering has high potential to clash between papers.   NS -Forest => potential solution for that too.

```[tasklist]
### Tasks
- [ ] https://github.com/obophenotype/cell-ontology/issues/2339
- [ ] https://github.com/obophenotype/cell-ontology/issues/2343
- [ ] https://github.com/obophenotype/cell-ontology/issues/2344
- [ ] https://github.com/obophenotype/cell-ontology/issues/2345
- [ ] https://github.com/obophenotype/cell-ontology/issues/2346
- [ ] https://github.com/obophenotype/cell-ontology/issues/2355
- [ ] add transcriptomic definition of cortinal Sncg interneurons
- [ ] add transcriptomic definition of cortical Pax6 interneuron
- [ ] add transcriptomic definition of cortical Lamp5 interneuron
- [ ] add transcriptomic definition of Lamp5 Lhx6 interneuron
- [ ] add transcriptomic definition of cortical Pax6 interneuron
```

```[tasklist]
### Tasks
```

**Comment by scheuerm** [comment]
@dosumis We've not analyzed these data yet, but we'll look into it.

**Comment by AvolaAmg** [comment]
I am building a work in progress [list](https://docs.google.com/spreadsheets/d/1S_A6UxadCZoApS-sNulYTsr2UsbPRRA3jmQO4lrmXQU/edit#gid=305058634) with definition for these cortical cells, with notes for discussion and tickets. This might change as the discussion follows. The astrocytes already have a Pull Request (#2328). 

Initially I started to mine the v1 specialised cells based on the relative number of nuclei dissected from areas that contribute to each cell type (Figure 5E). 

However, it is important to notice that the MERFISH data and the definition of cells as "v1 specialised" refer to another set of cells and it is not necessarly based on how enlarged is the population in that are (see image below). The specialisation of cells is based on _transcriptomic distinctiveness_ of cell types in each area compared to the same type of cell in another area. For Instance, in V1, cell types that had a different transcriptomic profile compared to the same cell types in other brain regions were considered V1 specific. These scores are present on the supplementary table S11 and they are visualised in Figure 6A. 


![image](https://github.com/obophenotype/cell-ontology/assets/81253886/8ca41917-4bdc-4f89-8424-be2d5fc39834)


To determine the V1 specialised cell types I suggest:
- Follow the scores from table S11 
- Consider the MERFISH results of figure 6 to categorise V1 specialised cell types
- Specify v1 specialised cell types based on their soma location in v1 and based on which layer their soma is located
- Mention in the comment of the description that their specialisation was attributed to their transcriptomic distinctiveness score >0.6.
- Potentially add NF forest markers scores as they would provide the minimum number of markers to define the cell types. 

**Side note, L5 ET projecting**

L5 ET project present distinct markers for brain area, some of them are showed in Figure 7D and supplementary table S13. 
I suggest to include an ACC L5 ET specific type, A1 specific type, DFC specific type based on their clear markers profile.



Finally, it might be necessary to revise the grouping terms for cortical neurons some examples in this [list](https://docs.google.com/spreadsheets/d/1S_A6UxadCZoApS-sNulYTsr2UsbPRRA3jmQO4lrmXQU/edit#gid=305058634). Happy to discuss about it.
>for instance It might be necessary to modify the grouping on CL for cell types downstream of [intratelencephalic-projecting glutamatergic cortical neuron](http://purl.obolibrary.org/obo/CL_4023008) and add subgrouping like i.e. IT projecting primary motor cortex neuron, IT middle temporal gyrus etc, IT visual cortex.

**Comment by dosumis** [comment]
From discussion in DOS group:  Consensus is to add types that group all region specific clusters under a specific subclass. e.g. for L4 IT.

The challenge is that we have 2 ways to do this.

1.  We could use cross area clustering + origin of dissection. e.g. v1 is in blue below:

![image](https://github.com/obophenotype/cell-ontology/assets/112839/234fd3c5-5c24-441d-affe-16a9c00ba20f)

=> reference = combination of  L2,3,4 and 6

OR 

2. We could use region specificity of within area clusters (fig 6 in paper).  This => L1-7 for within area
![image](https://github.com/obophenotype/cell-ontology/assets/112839/635b6ac7-745f-41c1-a626-ba7c5301aa00)

With this we can also add location from MerFISH.  

In both cases we could calculate NS forest markers.

IN either case, in order to add a link to data, we really need a corresponding annotation on the CxG dataset.

**Comment by dosumis** [comment]
For terms already in CL for cross area subclasses, we should add links to Jorstad as reference data,  consider adding NS-FOREST markers.  In all cases we should also review definition, e.g. definitions based on laminar location or markers are not always reliable for transcriptomically defined types.  

![image](https://github.com/obophenotype/cell-ontology/assets/112839/aac82143-815d-4cb2-a43a-ca10d0ce029f)

**Comment by AvolaAmg** [comment]
Find attached here some discussions/note and questions to ask to the author of the paper in this [document](https://docs.google.com/document/d/15Rzryq1bQkvM52xU2iOBwqVjKvXM0ShFr4G7hrfKhTI/edit?usp=sharing). 
Please comment if you want to add anything relevant to discuss with the author.

Here there is the [tracker](https://docs.google.com/spreadsheets/d/1S_A6UxadCZoApS-sNulYTsr2UsbPRRA3jmQO4lrmXQU/edit#gid=0) for potential cell terms to add based on the paper, there are two tabs, one refers to new terms to add based on the Cross-area taxonomy (Fig. 5E) and one refers to new terms to add based on V1 specialisation, area specific taxonomy and MERFISH data (Fig. 6).
