### ISSUE TITLE
Add definitions with transcriptomic reference for general cortical cell types

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2333]
For terms already in CL for  cortical neurons - cross area subclasses, we should add links to Jorstad[1] as reference data using cross-areal as the reference (The general classes for these cell types are almost identical between cross-area and within area subclasses.)

Consider adding NS-FOREST marker if available.  In all cases we should also review textual definitions, e.g. definitions based on laminar location or markers are not always reliable for transcriptomically defined types.  

![image](https://github.com/obophenotype/cell-ontology/assets/112839/aac82143-815d-4cb2-a43a-ca10d0ce029f)

[1] Jorstad, Nikolas L., Jennie Close, Nelson Johansen, Anna Marie Yanny, Eliza R. Barkan, Kyle J. Travaglini, Darren Bertagnolli, et al. 2023. “Transcriptomic Cytoarchitecture Reveals Principles of Human Neocortex Organization.” Science 382 (6667): eadf6812. https://doi.org/10.1126/science.adf6812. https://cellxgene.cziscience.com/collections/d17249d2-0e6e-4500-abb8-e6c93fa1ac6f
```[tasklist]
### Tasks
- [ ] https://github.com/obophenotype/cell-ontology/issues/2337
- [ ] https://github.com/obophenotype/cell-ontology/issues/2339
- [ ] https://github.com/obophenotype/cell-ontology/issues/2593
```

**Comment by scheuerm** [comment]
@dosumis maybe you know the answer to this......I am confused about the cross-area and within-area sub-classes/clusters.  In the data on cellxgene that I've looked at, they are using the same names, but the number of cells differ and the marker expression patterns differ so I'm not sure what I am dealing with.  I am planning on reaching out to Trygve to get clarification as well.

**Comment by dosumis** [comment]
Perfect - thanks!  Can you share call details with Alida & I?

**Comment by AvolaAmg** [comment]
Hi Both, 
I think the NF-forest markers will make a big difference for the text definition of these cell types. I think running them on the [Jorstad](https://doi.org/10.1126/science.adf6812) dataset would be ideal. Perhaps, the NF-forest analysis could be run on pooled datasets in CxG for this collection.
I will review the text definition for the CL terms listed below and see if I can include more morphological, electrophysiological, transcriptomic informations. In the comment section, I will mention that historically these cells were defined based on their layer positioning, but this definition has changed with transcriptomic informations.
This is the list of CL terms:

- [L2 intratelencephalic projecting glutametergic neuron](http://purl.obolibrary.org/obo/CL_4030060)
- [L2/3 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030059)
- [L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023047)
- [L3 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030061)
- [L4 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030063)
- [L4/5 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030062)
- [L4/5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023048)
- [L5 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030064)
- [L5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023049)
- [L6 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030065)
- [L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023050)
- [L6 intratelencephalic projecting Car3 glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030068)
- [L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex]()
- [L2/3 bipolar vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023007)
- [L5 vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023014)
- [L2/3 bipolar vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023007)
- [L5/6 cck, vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023019)


Another point to consider: 
the SST IT GABAergic cortical interneurons have in their text definition and in their cell label a specific link to Mmus (Also the VIP neurons mentioned above). Is it worth considering revising these definitions to see if there can be a universal definition encompassing also Homo sapiens and other primates? 
These are the cells: 
- [L2/3/5 fan Martinotti sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023030)
- [L4 sst Martinotti interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023031)
- [L5 non-Martinotti sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023028)
- [L5 sst T-Martinotti interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023027)
- [L5/6 non-Martinotti sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023118)
- [L6 th sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023075)

@dosumis, Should we consider adding the [Siletti paper](https://doi.org/10.1126/science.add7046) as a reference as well in the text definition for these cells?

**Comment by dosumis** [comment]
Re-opening because I feel like not fully completed given the original intent of this ticket.  Looking back at the original description of work - that intent could have been more clearly stated.  

What we need:  All cross-area subclass terms should have a definition following that standard t-type pattern.  So far we have these

<img width="184" alt="image" src="https://github.com/user-attachments/assets/590e2335-db8a-48dd-a791-a119e59b4ad4">


Needed - all cross-area subclass neurons

<img width="355" alt="image" src="https://github.com/user-attachments/assets/aa140dc5-06ad-44ab-9c42-ba9c63e6f09e">
<img width="340" alt="image" src="https://github.com/user-attachments/assets/ffab53b9-a28c-4d37-827b-4f145964a106">
<img width="359" alt="image" src="https://github.com/user-attachments/assets/dcac045c-9d3b-41e4-b4e5-19cb92e3004c">
<img width="347" alt="image" src="https://github.com/user-attachments/assets/ecf0e0a0-c46a-4ba9-812d-d785365fc131">

We need separate tickets for NS-Forest markers.  
 1. We should add them for all cross-area subclasses. <-- High priority.  We have these markers.  
 2. Review discussions/agreement for cross-area subclasses & make ticket.
