### ISSUE TITLE
Clean up hierarchy immediately under neuron

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2348]
If it is a grouping class: 
- Is It needed?
- Is classification under it complete?
- Is classification under it sustainable. Can we realistically populate classes - ideally with inferred classification.  If yes  - document required work on a new ticket
- Is it well defined - textually and logically?
If it is not a grouping class:
 - What taxonomic groupings does it apply to (can we add taxon restriction?) - useful to be able to separate out mammalian neuronal types from others.
 - Is it well defined - textually and logically (in this case this probably means having on necessary conditions for class membership - i.e. subclassof axioms but no EquivalentClass axioms
 - Can we axiomatise it so that it is no longer at the top level?

**Comment by AvolaAmg** [comment]
Not immediately under neuron, this is under interneuron, but it is a class hierarchy related to neurons #2357 .

**Comment by AvolaAmg** [comment]
- [ ] Merge [central nervous system neuron] with [CNS neuron (sensu vertebrata)]
- [ ] Move under [central nervous system neuron] the following terms: [columnar neuron] [commisural neuron] [hippocampal CA4 neuron] [interneuron] [kisspeptin neuron] [lateral ganglionic eminence derived neuron] [lateral line ganglion] [midbrain-derived inhibitory neuron] [multipolar neuron] [neural crest derived neuron] [olfactory bulb tufted cell] [trigeminal neuron]
- [ ] Move under [peripheral nervous system neuron] : [cardiac neuron] [polymodal neuron] [pseudounipolar neuron] [sensory processing neuron] [somatosensory neuron] [spiral ganglion neuron] [unipolar neuron] [photoreceptor cell] [retinal bipolar neuron]
- [ ] Adjust definition of [bistratified cell]
- [ ] Adjust definition of [columnar neuron]
- [ ] Adjust definition of [commisural neuron]
- [ ] Adjust definition of [polymodal neuron]
- [ ] Adjust definition of [sensory processing neuron]
- [ ] [Visual system neuron] and children cannot be grouped in this way and require an adjustment

**Comment by AvolaAmg** [comment]
Discussion to have:
@dosumis do we need to have the term [interneuron](http://purl.obolibrary.org/obo/CL_0000099) and the [CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) as two separate terms? Interneurons are only and exclusively present in the central nervous system, I think having two terms is redundant and we should merge them and have CNS interneuron has an exact synonym

**Comment by AvolaAmg** [comment]
Discussion to have:
@dosumis I think we need to merge [peripheral sensory neuron](http://purl.obolibrary.org/obo/CL_3000004) and [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) in one single term as all sensory neurons are in the periphery.

**Comment by AvolaAmg** [comment]
One more discussion @dosumis
CNS sensu invertebrate could be deleted as it has only exclusively Kenyon Cells underneath the terms and then the CNS sensu vertebrata can be merged with central nervous system neuron cell type

**Comment by AvolaAmg** [comment]
These cells should not be under neuron. I think it has to do with the soma location, substitute it with 'part of' some 'location in the nervous system'

![image](https://github.com/user-attachments/assets/a68292c0-2f22-4af6-a42b-5abe46611159)

**Comment by AvolaAmg** [comment]
have a look at the lateral line ganglion neuron. this neuron is found in fish, perhaps it would be possible to group it with the other primary and secondary sensory neurons (sensu Teleostei)
