### ISSUE TITLE
[Design pattern] neurotransmitter secretion grouping class

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2365]
**Context**

We have a set of grouping classes for grouping neuron types by neurotransmitter secretion.  It should be straightforward to write a DOSDP class to cover these.  Adding new ones will likely be rare, but we may occasionally have to   The basic pattern used is documented in the relations guide - see https://github.com/obophenotype/cell-ontology/issues/2362 

**Tasks**
- [ ] Update patterns of all subclasses of %CL class% to use standard pattern for %CL class% # Most already conform, but we could clean up the hierarchy adding more autoclassification.
- [ ] Add DOSDP pattern for grouping %CL class% # Check all already conform
- [ ] Update relations guide to include new standard pattern for %CL class% (Add link to DOSDP/ DOSDP markdown to relevant section

**Comments**

**Comment by dosumis** [comment]
Simple example to practise writing DOSDPs
