### ISSUE TITLE
Populate cell types under 'fenestrated' endothelial cell

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2424]
There are many types of fenestrated endothelial cell, but we only have a couple of classes under this term ('fenestrated cell' ; CL_0000666 ) 

Some examples + papers to curate:
https://www.perplexity.ai/search/which-endothelial-cell-types-a-IMYlTiBZRi.MU99.CRfyHA

see also #2423
```[tasklist]
### Tasks
- [ ] https://github.com/obophenotype/cell-ontology/issues/2474
- [ ] https://github.com/obophenotype/cell-ontology/issues/2476
- [ ] #2481
- [ ] https://github.com/obophenotype/cell-ontology/issues/2485
- [ ] https://github.com/obophenotype/cell-ontology/issues/2484
- [ ] https://github.com/obophenotype/cell-ontology/issues/2486
```

**Comment by dosumis** [comment]
Related issue:

GO has this term:

glomerular endothelium fenestra
http://purl.obolibrary.org/obo/GO_0036053

We should add a has_part relationship to this to the relevant CL term

Also - of the fenestrated capillary cells mentioned in the Perplexity response, we only have this one  "peritubular capillary endothelial cell" - others will need to be new terms.

**Comment by dosumis** [comment]
I think we should request a general term for endothelia cell fenestra from GO.

label: endothelia cell fenestra
def: A transcellular pore present in some types of endothelial cell, that facilitates efficient transfer of molecules across endothelia.

I think also possible to make more subclasses where there are clear differences in structure, e.g.  - presence/absence fenstra diaphragm & presence/absence associated basal lamina.  There are a few possiblilities for GO annotation - structural proteins of diaphragm and proteins that regulate formation and pore size.

See https://www.perplexity.ai/search/which-endothelial-cell-types-a-IMYlTiBZRi.MU99.CRfyHA

https://github.com/geneontology/go-ontology/issues/new?assignees=&labels=New+term+request&projects=&template=new-term-request.md&title=NTR%3A+%5Bproposed+new+term+label%5D
