### ISSUE TITLE
Complete NTRs & edits required for mapping of Gut Cell Atlas terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2560]
- [x] https://github.com/obophenotype/cell-ontology/issues/2580

- [x]  Enterocyte - Late (APOA1, APOC3, APOB, GUCA2A, CDHR5) - decided this is same as enterocyte

- [x]  https://github.com/obophenotype/cell-ontology/pull/2465
`
- [x]  https://github.com/obophenotype/cell-ontology/issues/2562 -  -Not added anymore -  the same as the existing term `intestinal crypt stem call term `

- [x]  https://github.com/obophenotype/cell-ontology/issues/2563

- [x]  https://github.com/obophenotype/cell-ontology/issues/2476 This is a specialised, fenestrated endothelial cell - check with experts whether this is appropriate mapping for their capillary cell.
- [x] https://github.com/obophenotype/cell-ontology/issues/2576

- [x]  https://github.com/obophenotype/cell-ontology/issues/2564

- [x] [Subepithelial fibroblasts and subclasses](https://github.com/obophenotype/cell-ontology/issues/2567)
- [x] https://github.com/obophenotype/cell-ontology/issues/2586
- [x] https://github.com/obophenotype/cell-ontology/issues/2587 - ticket is made but waiting for an uberon term `follicle associated epithelium `
- [x] https://github.com/obophenotype/cell-ontology/issues/2586

- [x]  [#2589](https://github.com/obophenotype/cell-ontology/issues/2589)

- [x] https://github.com/obophenotype/cell-ontology/issues/2558

- [x] https://github.com/obophenotype/cell-ontology/issues/2578

- [x] https://github.com/obophenotype/cell-ontology/issues/2517

- [x] Immature Pericyte https://github.com/obophenotype/cell-ontology/issues/2503

- [x] Review mapping sheet for missing mappings

(almost all done - might be a few very recently added terms to map)
 

- [x] Check for all cases where there is a validated CellGuide description

@Caroline-99 - work on simple script to lookup and report -  [matched_validated_descriptions_gut_atlas](https://docs.google.com/spreadsheets/d/1gFkMaah9X6544SFigmZH92A-fyGzpdQj_AjPkmSksWg/edit?usp=sharing)

- [x]  Review validated CellGuide descriptions for addition

check no contradiction with CL def

- [x]  Run GCA hierarchy through validator

(https://github.com/hubmapconsortium/validation-template) - requires reformatting. Try using ChatGPT to reformat. <-- stretch goal

**Comment by JABelfiore** [comment]
Following cell terms removed as they are not in the updated version of the GCA hierarchy
- [ ] Immune Organizing Fibroblast (mLN stroma)
- [ ] Crypt Support fibroblast #2558 
- [ ] Villus Support fibroblast
- [ ] Immune Organizing Fibroblast (mLN stroma)

Following cell terms added from updated GCA hierarchy:
- [ ]Subepithelial fibroblasts (S2)
- [ ]Lamina propria fibroblasts (S1)
- [ ]Submucosal Fibroblasts (aka Crypt Support/Trophocytes/S3)
- [ ]Fibroblastic reticular cells

**Comment by Caroline-99** [comment]
There are 69 terms with a validated CellGuide description: [matched_validated_descriptions_gut_atlas](https://docs.google.com/spreadsheets/d/1gFkMaah9X6544SFigmZH92A-fyGzpdQj_AjPkmSksWg/edit?usp=sharing)

**Comment by aleixpuigb** [comment]
Some of the cells are restricted in the intestinal compartment but contain the term 'gut' either in the label, the definition or both. The gut comprehends more structures than the intestine, such as the stomach or the esophagus, and the presence of intestinal cells in there might indicate pathology (e.g., Barret's esophagus). For example, `transit amplifying cell of gut` should be `intestinal transit amplifying cell`.
CC @emquardokus
