### ISSUE TITLE
Add t-type definition to all the Jorstad CrossArea_Subclass with CxG reference

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2593]
```[tasklist]
### Tasks
- [x] [pvalb GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023018)
- [x] [sst GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023017)
- [x] [sst chodl GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023121)
- [x] [lamp5 GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023011)
- [ ] https://github.com/obophenotype/cell-ontology/issues/2595
- [x] [sncg GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023015)
- [x] [VIP GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)
- [x] [chandelier pvalb GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023036)
- [x] [astrocyte of the cerebral cortex](http://purl.obolibrary.org/obo/CL_0002605)
- [x] [cerebral cortex endothelial cell](http://purl.obolibrary.org/obo/CL_1001602)
- [x] [microglia cell](http://purl.obolibrary.org/obo/CL_0000129)
- [x] [oligodendrocyte precursor cell](http://purl.obolibrary.org/obo/CL_0002453)
- [x] [vascular leptomeningeal cell](http://purl.obolibrary.org/obo/CL_4023051)
- [x] [L5 extratelencephalic projecting glutamatergic cortical neuron](http://purl.obolibrary.org/obo/CL_4023041)
- [x] [L5/6 near-projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030067)
- [x] [L6 corticothalamic-projecting glutamatergic cortical neuron](http://purl.obolibrary.org/obo/CL_4023042)
- [x] [L6b glutamatergic cortical neuron](http://purl.obolibrary.org/obo/CL_4023038)
```

**Comment by AvolaAmg** [comment]
example of a t-type definition 
This is for L2/3 intretelencephalic projecting glutamatergic neuron
> A transcriptomically distinct intratelencephalic-projecting glutamatergic neuron with a soma found between cortical layer 2-4. This intratelencephalic-projecting glutamatergic neuron has thin-tufted apical dendrites and extends its axonal projection into L5 in the neocortex. This neuronal type has a hyperpolarised resting membrane potential. The standard transcriptomic reference data for this cell type can be found on the CellxGene census under the collection: 'Transcriptomic cytoarchitecture reveals principles of human neocortex organization', dataset: 'Supercluster: IT-projecting excitatory neurons', Author Categories: 'CrossArea_subclass', clusters L2/3 IT.
