### ISSUE TITLE
BG taxonomy class level terms to add/map

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2626]
Terms to Map/Add for class level BG taxonomy

- [ ]  'CN MGE LAMP5 GABA',
- [ ]  'CN CGE VIP GABA',
- [ ]  'SN PVALB GABA',
- [ ]  'CN LHX6 LHX8 GABA',
- [ ]  'STR D1 MSN GABA',
- [ ]  'STR Granular GABA',
- [ ]  'STR D2 MSN GABA',
- [ ]  'GP PVALB GABA',
- [ ]  'STR Hybrid MSN GABA',
- [ ]  'TH MEIS2 GABA',
- [ ]  'BN MEIS2 GABA',
- [ ]  'SN STH GABA',
- [ ]  'STR SST GABA',
- [ ]  'STR Cholinergic GABA',
- [ ]  'BG PVALB GABA',
- [ ]  'BG Glut',
- [ ]  'TH Glut',
- [ ]  'SN TH Dopa',
- [ ]  'GP GABA Glut'

Anatomy based on abbreviations in DHBA/HBA:

CN - (DHBA) "cerebral nuclei"; id "DHBA:10331"; "CN"; "http://atlas.brain-map.org/atlas?atlas=138322603#structure=10331"
SN - (DHBA) "substantia nigra"; "DHBA:12251";  "SN";  "http://atlas.brain-map.org/atlas?atlas=138322603#structure=12251"
STR - (DHBA) "striatum"; "DHBA:10333"; "STR"; "http://atlas.brain-map.org/atlas?atlas=138322603#structure=10333"
GP - (DHBA) "globus pallidus";  "DHBA:10342";  "GP";  "http://atlas.brain-map.org/atlas?atlas=138322603#structure=10342"
TH - (HBA) "thalamus";  "TH"; database_cross_reference "http://atlas.brain-map.org/atlas?atlas=265297125#structure=4392" (DHBA uses this for "medial division of PPHC (area TH)")
BN - (HBA) "basal nuclei (basal ganglia)"; "DHBA:10332"; "BN";  "http://atlas.brain-map.org/atlas?atlas=138322603#structure=10332"
BG - (HBA) "basal ganglia";  "BG"; "http://atlas.brain-map.org/atlas?atlas=265297125#structure=4276"  (DHBA uses BG to refer to band of Giacomini)

**Comment by addiehl** [comment]
The CL term that generally refers to immune cells is 'leukocyte' CL:0000738, which already includes 'immune cell' as a related synonym.

'leukocyte' is the ancestor to all major immune cell types, i.e. lymphocytes (T cells, B cells, innate lymphoid cells), dendritic cells, monocytes and macrophages, mast cells, and granulocytes. The reason we haven't made 'immune cell' an exact synonym is that there are a few cell types of non-hematopoietic lineages that play significant roles in the functioning of the immune system, such as follicular dendritic cells (which are not at all like the other dendritic cells), the endothelial cells of the high endothelial venues and a few others like M cells.  These non-hematopoietic "immune" cells are all cells found in very particular anatomical locations, and are thus unlikely to be the cells that are identified as immune cells in any kind of transcriptional analysis.

**Comment by dosumis** [comment]
@AvolaAmg   - do you think we will need superclasses to cover SST CHODL GABA, LAMP5 GABA etc independent of region?
Does the Whole mouse brain support groupings like that?

**Comment by dosumis** [comment]
General issue - Cerebral nuclei in Uberon has no children (subClassOf or part_of).

In DHBA it has 

![image](https://github.com/user-attachments/assets/8b08d6c4-d9b3-4457-861c-c560c12b0943)

i.e. it covers the basal ganglion.  This fits with the draft taxonomy:

Subpallium GABA | CN CGE GABA | CN CGE VIP GABA | STR VIP GABA
-- | -- | -- | --

(STR= striatum)

1. Make Uberon ticket to update Uberon
2. In the meantime we will need to rely on manual classification of CN neuronal subtypes by location.

**Comment by AvolaAmg** [comment]
so far there I cannot find any literature evidence that specifically focuses on neurons that are specifically in the cerebral nuclei and they are derived from Caudal, Medial and Lateral ganglionic evidence. Additional literature research will be needed from BICAN to define these cell types

**Comment by dosumis** [comment]
It may be that the evidence for dev origin is entirely from transcriptional similarity.  I think best to check with Nelson & Morgan.

Can you link related Uberon ticket here?

**Comment by AvolaAmg** [comment]
https://github.com/obophenotype/uberon/issues/3171
https://github.com/obophenotype/uberon/issues/3176
https://github.com/obophenotype/uberon/issues/3254

**Comment by dosumis** [comment]
Might be better to start a new ticket, but adding some comments here for now.

The major tension we need to deal with is between simple definitions based on expression of one or two genes vs T-types.

The problem is illustrated in the example below:  

If we define Lamp5 GABAergic cortical interneuron as any GABAergic cortical interneuron expressing LAMP5, then this will encompass transcriptomically distinct Lamp5 Lhx6 neurons.  

![Image](https://github.com/user-attachments/assets/7a5555ba-ba0c-4a8b-970c-c7559365d092)

I worry that we already have some cases where this could cause problems in BG and that some planned terms on this ticket will suffer from similar problems.  We have other cases of T-types at the cluster (leaf node) level of taxonomies that do not express the gene that they are named for.

Better, in these cases, to wait for consensus to emerge on BG T-types and concentrate on more general/classical types for now.  At the very least, we should avoid genes in EquivalentClass defs.
