### ISSUE TITLE
[EPIC] New terms and editions for Human Retinal Cell Atlas

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2647]
There are multiple new cell types + CL edits that are needed for the Human Retinal Cell Atlas:
- [x] #2651
- [x] #2892
- [ ] Add 'in orthology relationship with' in species-specific retinal cell types
- [ ] NTR VIP immunoreactive amacrine cell
- [ ] NTR vGlut3 amacrine cell
- [ ] NTR NOS-positive amacrine cell 1, 2 and 3
- [ ] NTR CA2 cell (weak dopaminergic cell)
- [ ] NTR Dopaminergic amacrine cell
