### ISSUE TITLE
Reproductive System Jamboree New Terms 

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2683]
Ovary (14 terms)

- [x] #2527 
- [x] #2733 
- [x] #2528
- [x] #2528
- [x] #2602
- [x] #2602
- [x] atretic granulosa cell #2728
- [x] early luteal cell -  #2980 
- [x] late luteal cell -  #2980 
- [x] steroidogenic stromal cell -  https://doi.org/10.7554/eLife.77239

Fallopian tube (7 terms)

- [x] #2623
- [x] #2623
- [x] #2682
- [x] unclassified fallopian progenitor cell (USFP) - https://github.com/obophenotype/cell-ontology/issues/3196#issuecomment-3074417651

Uterus (6 terms)

- [x] #2687 
- [x] #2687 
- [x] stromal cell of uterus (need to discuss with Valentina or Roser)  #2784
- [x] #2688 
- [x] uNK1 #2984 
- [x] uNK2 #2991 
- [x]  uNK3 #2992 
- [x] Re-label glandular cell of endometrium & improve classifications  #2695
- [x] #2986 

Schematics figures:

- [x] Update the figures of the three organs to reflect what is currently in CL.
- [x] In text legend - include details if labels have been changed in CL 
- [x] Look into the table in the paper to check any labels with **CL IDs TBC**

DEADLINE - 13th of March 2025

**Comment by aleixpuigb** [comment]
From 27/02/2025 call:

- [ ] Instead of small and large luteal cell, include early and late luteal cell [https://www.biorxiv.org/content/10.1101/2024.12.15.628550v1.full](https://www.google.com/url?q=https://www.biorxiv.org/content/10.1101/2024.12.15.628550v1.full&sa=D&source=docs&ust=1740676709055977&usg=AOvVaw0-elTcIcFcAcVzm8Bs63z0)
- [ ] Find a way how to make oocyte part of the follicular cell of ovary without incurring to taxon constraint issues (insects have oocytes)

**Comment by dosumis** [comment]
> Find a way how to make oocyte part of the follicular cell of ovary without incurring to taxon constraint issues (insects have oocytes)

Aren't follicular cells somatic in both cases?
