### ISSUE TITLE
[NTR]: tuft cell of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#792]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

Preferred term label:
tuft cell of large intestine

Synonyms
brush cell of large intestine; tuft cell of epithelium of large intestine; brush cell of epithelium of large intestine

Definition (free text, please give PubMed ID in format PMID:XXXXXX)
Intestinal tuft cells are a morphologically unique cell type, best characterized by striking microvilli that form an apical tuft. These cells represent approximately 0.5% of gut epithelial cells depending on location. PMID: 29714721

Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):
brush cell: http://purl.obolibrary.org/obo/CL_0002204
intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250

What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon
large intestine: http://purl.obolibrary.org/obo/UBERON_0000059

Your nano-attribution (ORCID)
0000-0003-4183-8865

Any additional notes or concerns

**Comment by ngeorgeebi** [comment]
could instead add these terms as synonym to brush cell of epithelium proper of large intestine http://purl.obolibrary.org/obo/CL_0002203

**Comment by dosumis** [comment]
@mkeays - looks related to terms you've added recently.

**Comment by ngeorgeebi** [comment]
@mkeays Hi Maria, hope you're well. They are similar to @sfexova's terms for the previous anatomograms. These are for the gut :) please feel free to get in touch with me to discuss!

**Comment by mkeays** [comment]
@ngeorgeebi hi Nancy! I just recently added a general term for "intestinal tuft cell" (#780); CL already has ["brush cell of epithelium proper of large intestine"](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002203) -- do you think "tuft cell of large intestine" could be a synonym of this?

**Comment by ngeorgeebi** [comment]
Hi @mkeays sounds good! I noticed that CL term too :) apologies I hadn't realised at the time. I did make a comment above thinking exactly the same as you suggested so great that we are on the same page!:
ngeorgeebi commented 3 days ago
could instead add these terms as synonym to brush cell of epithelium proper of large intestine http://purl.obolibrary.org/obo/CL_0002203 

Would be happy to see these added as synonyms. Thanks!

**Comment by mkeays** [comment]
Hi @ngeorgeebi , ahh sorry, I missed your comment! OK great, I can add the synonyms to the existing term then I think -- @paolaroncaglia do you think that sounds OK?

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi and @mkeays ,
 
If Nancy’s requested ‘tuft cell of large intestine’ is indeed located in the intestinal epithelium, as Nancy’s suggested synonyms suggest, then I agree that ‘tuft cell of large intestine’ could be a synonym of the existing term CL_0002203 ‘brush cell of epithelium proper of large intestine’. 

This said, looking at the whole ‘brush cell’ node, and considering Nancy’s request for ‘tuft cell of small intestine’ https://github.com/obophenotype/cell-ontology/issues/791, I’d suggest the following edits:

- [ ] If possible, add some gloss to the definition of ‘brush cell’. It is currently “A cell type found in the gastrointestinal and respiratory tracts that is characterized by the presence of a tuft of blunt, squat microvilli (120-140 per cell). Function of this cell type is not known.” This is from 2010 so I wonder if we could say something about function now?

- [ ] If the above can be addressed, then we could remove this bit from the def of its child ‘brush cell of trachebronchial tree’” “…Function not known.”.

- [ ] Are brush cells located in bronchus or trachea ever referred to as “tuft cells” in the literature? If yes, we should ensure that 'brush cell of trachebronchial tree’, 'brush cell of bronchus’, 'brush cell of lobular bronchiole’, ‘'brush cell of terminal bronchiole’, and 'brush cell of trachea' all have synonyms containing the “tuft” wording.

- [ ] Maria wrote in her ticket on ’intestinal tuft cell’ (https://github.com/obophenotype/cell-ontology/issues/780): “CL has a general brush cell and brush cell of epithelium proper of large intestine but no general intestinal brush cell. Brush cells found in small and large intestine seem to be called "tuft cells" rather than "brush cells" (https://en.wikipedia.org/wiki/Tuft_cell). They share some characteristics, such as marker proteins, so it would be good to have one that was not limited to large intestine.”. It’d be nice to clarify that in the definition, i.e. why the label has tuft instead of brush (and xref the Wikipedia entry version), and also if possible some gloss to clarify what differentiates intestinal tuft cells from generic tuft/brush cells please. Perhaps also use Nancy’s suggestion: “Any brush cell that is part of the intestinal epithelium. [In what species is the following known?] Intestinal tuft cells represent approximately 0.5% of gut epithelial cells depending on location.” and add xref PMID:29714721.

- [ ] If Maria is confident that the primary label should refer to tuft instead of brush for intestinal types, then the label of CL_0002203 ‘brush cell of epithelium proper of large intestine’ should be changed to ‘tuft cell of epithelium proper of large intestine’ (keep ‘brush cell of epithelium proper of large intestine’ as an exact synonym). Also, the following annotations should be added to CL_0002203 from Nancy’s ticket https://github.com/obophenotype/cell-ontology/issues/792:
develops_from ‘intestinal crypt stem cell’ if that’s what Nancy meant?
database_cross_reference: Nancy’s ORCID 0000-0003-4183-8865 should be added - does CL use database_cross_reference if the person adding the term (say Maria or myself) is not the same as the person requesting it?
synonyms:
tuft cell of large intestine [broad]
brush cell of large intestine [broad]
tuft cell of epithelium of large intestine [exact or broad?]
brush cell of epithelium of large intestine [exact or broad?]

- [ ] Add a new term to address Nancy’s request for ‘tuft cell of small intestine’ https://github.com/obophenotype/cell-ontology/issues/791, and model it on the existing “sibling” CL_0002203 ‘brush cell of epithelium proper of large intestine’:
(#791 can be closed as duplicate)
label: tuft cell of epithelium proper of small intestine
parents: 
subclass of ’brush cell’; 
while ‘intestinal crypt stem cell’ should probably be linked via ‘develops from’ if that’s what Nancy meant?
and part_of uberon ‘small intestine’
def: “Any intestinal tuft cell located in the epithelium proper of small intestine.” Can anything else be said to differentiate this term from its parent and/or sibling?
synonyms: brush cell of small intestine [broad]; tuft cell of epithelium of small intestine [exact or broad?]; brush cell of epithelium of small intestine [exact or broad?]; brush cell of epithelium proper of small intestine [exact]
Nancy’s ORCID 0000-0003-4183-8865 should be added, as a database_cross_reference or elsewhere as resolved above.

Did I forget anything :-) 
I can do the edits and ask for review, unless Maria prefers to take this on. Please feel free to provide feedback on any of my question marks as I haven’t done any serious reading on brush/tuft cells yet.
Thanks!

**Comment by mkeays** [comment]
Hi @paolaroncaglia , thanks so much for the detailed review. It all sounds good to me, if you don't mind doing the edits that would be great! From what I read it seemed to me that people tended to use "tuft cell" when talking about intestinal populations, and "brush cell" when talking about those in the respiratory tract, but there is some crossover. There was some suggestion that they have chemosensory function in what I briefly read, but I would have to research further to fully understand what is now known about these cells.

**Comment by cerivs** [comment]
Are brush cells in the intestine cells with the GO cellular component "brush border" GO:0005903 ?  If so lower vertebrates don't usually call them tuft cells.  They call them "brush border" cells.   In zebrafish researchers refer, very occasionally, to neuroepithilal cells in olfactory organ as tufted cells.   We seem to have very similar cells in the columnar/cuboidal epithelial cell tree we have 

 brush border epithelial cell
    enterocyte
            enterocyte of epithelium of duodenal gland
            enterocyte of epithelium of large intestine
            enterocyte of epithelium of small intestine
-

**Comment by dosumis** [comment]
From a quick naive look at Wikipedia:  looks like tuft cells are chemosensory cells (https://en.wikipedia.org/wiki/Tuft_cell) distinct from the brush border cells (entorcytes? )https://en.wikipedia.org/wiki/Brush_border.

If chemosensory - we should add SubClassOf: capable_of  some 'detection of chemosensory stimulus'

**Comment by paolaroncaglia** [comment]
Update: at the CL meeting today, @addiehl kindly agreed to look into this before the end of the year.

**Comment by paolaroncaglia** [comment]
@addiehl 

> Update: at the CL meeting today, @addiehl kindly agreed to look into this before the end of the year. We want to make sure that the nomenclature is consistent and unambiguous across species/anatomical areas.

Happy new year! I hope all is well. In a couple of days I'll meet the curator from the Single Cell Expression Atlas who opened this ticket. If you had a chance to look into this issue, could you please comment? Or let us know if you need more time. Thank you in advance for your precious feedback!

All the best,
Paola

**Comment by ngeorgeebi** [comment]
@paolaroncaglia sorry to be a pain! Just going through the NTR's i'd made - wondering if tuft cell of small intestine is going to be added? The original ticket was closed but i don't see any further discussion on this. Happy to help if needed! :)

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> Just going through the NTR's i'd made - wondering if tuft cell of small intestine is going to be added? The original ticket was closed but i don't see any further discussion on this. Happy to help if needed! :)

'tuft cell of small intestine' hasn't been added yet because we haven't resolved the nomenclature/classification disambiguation issue yet. @addiehl had [kindly offered to look into it](https://github.com/obophenotype/cell-ontology/issues/792#issuecomment-746596689) but I'm afraid he hasn't had a chance yet. 

@dosumis 
Shall I go ahead with the main parts of my suggestion [here](https://github.com/obophenotype/cell-ontology/issues/792#issuecomment-718095017) so Nancy has the term(s) she needs, and then Alex may review the nomenclature issue? 
Nancy, if we do change the nomenclature down the line, the CL ID will stay the same but the label may be different, hopefully that wouldn't break anything in your pipeline?

Thank you all,
Paola

**Comment by addiehl** [comment]
Paola,

I am still meaning to look into this, but have found little time to do so in recent weeks.  Go ahead and make your changes so that annotation work is not held up.

Thanks,
Alex

**Comment by paolaroncaglia** [comment]
@addiehl thank you very much for your prompt response! I fully understand.
@ngeorgeebi , I hope to work on this ticket next week.
Best,
Paola

**Comment by ngeorgeebi** [comment]
apologies @paolaroncaglia sorry but i'd rather err on the side of caution, I think if the label changes but the cell ID doesn't it does actually hit our pipeline as we use the term to do the mapping so it would create a mismatch via Zooma :/
sorry for the bother

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> apologies @paolaroncaglia sorry but i'd rather err on the side of caution, I think if the label changes but the cell ID doesn't it does actually hit our pipeline as we use the term to do the mapping so it would create a mismatch via Zooma :/
> sorry for the bother

Thanks, I'll keep this in mind. However, please note that, in general, any ontology term used in your pipeline may occasionally incur in a change of label, if the source ontology has reasons to believe that a label should be improved. We'll aim at including lists of new, modified and obsoleted terms in release notes for CL and Uberon, as you rightfully asked (EFO and Mondo already do that), but it would then fall on SCA developers to review the release notes. If I see a term with the subset tag "location_grouping" I'll be aware that it's used by the SCA, but in general, source ontologies have little way of knowing if/how a label change may affect downstream users... If needed, perhaps you could add this topic for discussion at our next HCA/SCA curators' meeting?

Thanks,
Paola

**Comment by ngeorgeebi** [comment]
@paolaroncaglia just checking in on this ticket! Is everything ok? I think we would actually need a specific term for tuft cell of large intestine as these cells might turn up in the other zoom images that we are creating - e.g. appendix but can make the more general term and have this as a child term of that would absolutely be ok

many thanks
Nancy

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
I was waiting to address this ticket because of the name change/SCA pipeline potential issue (see my previous comment and the agenda minutes/action items from our last monthly curators call). To avoid blocks, I can assume that the SCA pipeline issue will be addressed and that any necessary change in term labels will be acceptable. Please let me know. Thanks!

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia yes, please go ahead and we will deal with any issues further down the line. :)

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

Looking back at this ticket and as agreed previously, I added the following synonyms to the existing term CL_0002203 'brush cell of epithelium proper of large intestine':
"brush cell of large intestine"
"tuft cell of epithelium of large intestine"
"tuft cell of large intestine"
As a reminder, a new term 'tuft cell of large intestine' wasn't created because it would be entirely equivalent to CL_0002203 'brush cell of epithelium proper of large intestine', by virtue of its ontology axioms.
So you may use CL_0002203 'brush cell of epithelium proper of large intestine' for SCA anatomograms if needed.
The new synonyms will be visible in the next CL release (may be some time, as CL was last released last Friday).
I'll review the other suggested action items in this ticket later on, as they are not immediately needed for the anatomograms.
Any concern please let me know.

Thanks,
Paola

**Comment by sfexova** [comment]
Hi @paolaroncaglia - for the anatomograms, we will actually need a different term, 'tuft cell of colon' - should I open a new ticket for it?
(and yes, tuft cells appear to be chemosensory: https://www.frontiersin.org/articles/10.3389/fpsyt.2020.00436/full, although that has probably been resolved already)

**Comment by paolaroncaglia** [comment]
- [ ] 'tuft cell of appendix' should not reason under 'tuft cell of colon'

**Comment by paolaroncaglia** [comment]
@sfexova 

> for the anatomograms, we will actually need a different term, 'tuft cell of colon' - should I open a new ticket for it?

CL:0009041 'tuft cell of colon'

> (and yes, tuft cells appear to be chemosensory: https://www.frontiersin.org/articles/10.3389/fpsyt.2020.00436/full, although that has probably been resolved already)

Thanks for your feedback!
Paola
