### ISSUE TITLE
EPIC - Clean up CL editor documentation

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#959]
We now have documentation managed using mkdocs and released to https://obophenotype.github.io/cell-ontology/
(For details of how to update see )

The docs themselves need cleaning up and extending - with some material being pushed to more generic documentation

  -  [ ] index.md # Extend with more general info. Make clear split into user docs & editor docs.
  -  [ ] Keeping_ontology_terms_up_to_date.md.  # Move to user facing section of doc
  - annotation_properties.md # This should probably be promoted to generic ODK doc.  Needs reformatting as table doesn't work with 
  - [ ] presentations.md # File under user docs
  - [ ] relations_guide.md. # Important - promote to to of index.
  - [ ] resolving_merge_conflicts.md # Extend with screenshots & robot commands.  Could be promoted to more generic doc on GitHub workflows for ontologies?
